CREATE INDEX `ai_conversations_userId_idx` ON `ai_conversations` (`userId`);--> statement-breakpoint
CREATE INDEX `backtests_userId_createdAt_idx` ON `backtests` (`userId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `brain_decisions_userId_robotId_createdAt_idx` ON `brain_decisions` (`userId`,`robotId`,`createdAt`);--> statement-breakpoint
CREATE INDEX `broker_connections_userId_idx` ON `broker_connections` (`userId`);--> statement-breakpoint
CREATE INDEX `copy_trades_followerId_idx` ON `copy_trades` (`followerId`);--> statement-breakpoint
CREATE INDEX `copy_trades_traderId_idx` ON `copy_trades` (`traderId`);--> statement-breakpoint
CREATE INDEX `daily_pnl_userId_date_idx` ON `daily_pnl` (`userId`,`date`);--> statement-breakpoint
CREATE INDEX `daily_pnl_userId_robotId_idx` ON `daily_pnl` (`userId`,`robotId`);--> statement-breakpoint
CREATE INDEX `financial_goals_userId_status_idx` ON `financial_goals` (`userId`,`status`);--> statement-breakpoint
CREATE INDEX `marketplace_listings_isActive_idx` ON `marketplace_listings` (`isActive`);--> statement-breakpoint
CREATE INDEX `marketplace_listings_robotId_idx` ON `marketplace_listings` (`robotId`);--> statement-breakpoint
CREATE INDEX `portfolio_assets_userId_idx` ON `portfolio_assets` (`userId`);--> statement-breakpoint
CREATE INDEX `risk_settings_userId_idx` ON `risk_settings` (`userId`);--> statement-breakpoint
CREATE INDEX `robot_brain_userId_robotId_idx` ON `robot_brain` (`userId`,`robotId`);--> statement-breakpoint
CREATE INDEX `robots_market_idx` ON `robots` (`market`);--> statement-breakpoint
CREATE INDEX `robots_iaScore_idx` ON `robots` (`iaScore`);--> statement-breakpoint
CREATE INDEX `social_posts_createdAt_idx` ON `social_posts` (`createdAt`);--> statement-breakpoint
CREATE INDEX `social_posts_userId_idx` ON `social_posts` (`userId`);--> statement-breakpoint
CREATE INDEX `trades_userId_openedAt_idx` ON `trades` (`userId`,`openedAt`);--> statement-breakpoint
CREATE INDEX `user_robots_userId_idx` ON `user_robots` (`userId`);--> statement-breakpoint
CREATE INDEX `user_robots_robotId_idx` ON `user_robots` (`robotId`);